### ISSUE TITLE
How to contribute this project?

### ISSUE THREAD

**Issue by moutend** [code-check/codecheck#64]
Hi.
I want to contribute this project, but it has no guides for contributors such as CONTRIBUTING.md.
How can I make changes to this project and send PRs?

Anyway, `package.json` doesn't specify the nodejs version.
The codes in this project uses bluebird, the polyfil for Promise so that I guess this project targets older nodejs version such as v0.12.
I don't know why it depends on older version but I think it should specify the version at least.

Thank you.

**Comment by TsubasaK111** [comment]
@shunjikonishi review me! :D

**Comment by shunjikonishi** [comment]
@moutend 
Thank you for commenting.

What kind of contribute do you want?
node version issue?

**Comment by moutend** [comment]
@shunjikonishi  Simply, I want to know how to contribute this project. Like adding `--help` flag into codecheck command.

However, I can't run `mocha` in this project because `test/config.json.js:2` depends on an internal module that is not public.
I can send a PR but I think the PR that is not tested is unsuitable to contribute.

**Comment by shunjikonishi** [comment]
@moutend 
Though this project is public, we are going to maintain this project internally at least now.
Sorry.

If you have some opinion about this project, please let us know in Issue.

Thanks.

**Comment by moutend** [comment]
@shunjikonishi Now I know state of this project, thank you :+1:
