### ISSUE TITLE
codecheck fails when given 1M integers

### ISSUE THREAD

**Issue by hamko** [code-check/codecheck#86]
# how to reproduce
clone this branch and run `codecheck` or `codecheck > a`
https://github.com/code-check/challenge-more-green-grass/tree/super-large-input

# behavior
This branch has super-large in/out files (`test/in/999*, test/out/999*`). `test/basic.js` tests such super-large in/out 12 times. 

If you run just `codecheck`, 6 out of 12 spawn functions fails.
![_204](https://user-images.githubusercontent.com/3013271/39952942-12ae8a2a-55dc-11e8-882b-ee8cf01976bd.png)

If you run `codecheck > a`, spawn functions success.
![_205](https://user-images.githubusercontent.com/3013271/39952943-14351e2c-55dc-11e8-8d2a-f0ecb26b866a.png)

**Comment by hamko** [comment]
それが真ならば、メモリを使い果たしたらその後のテストケースは全て落ちるのが想定になりますか？

**Comment by shunjikonishi** [comment]
```
const app = codecheck.consoleApp(process.env.APP_COMMAND).consoleOut(false);
```

としたらテスト通った。(mochaのtimeoutの延長も必要)

NodeJSの標準出力のバッファリングに問題があるのかも。

**Comment by shunjikonishi** [comment]
テストの書き方を変えることで対応した。
stdoutをバッファリングした場合のOutOfMemoryなので、動作自体は問題ない。
